services:
    
    document.GoodsPackaging:
        class: ReservesBundle\Document\GoodsPackaging
        public: true
        calls:
            - [ setContainer, [ '@service_container' ] ]
    
    document.Inventory:
        class: ReservesBundle\Document\Inventory
        public: true
        calls:
            - [ setContainer, [ '@service_container' ] ]
