<?php

namespace OrderBundle\Repository;

/**
 * ClientOrderItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientOrderItemRepository extends \Doctrine\ORM\EntityRepository
{
}
