<?php

namespace OrderBundle\Repository;

/**
 * GoodsRequestAnnulRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodsRequestAnnulRepository extends \Doctrine\ORM\EntityRepository
{
}
