<?php

namespace OrderBundle\Repository;

/**
 * OrderDocRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderDocRepository extends \Doctrine\ORM\EntityRepository
{
}
