<?php

namespace OrderBundle\Repository;

/**
 * OrderAnnulRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderAnnulRepository extends \Doctrine\ORM\EntityRepository
{
}
