<?php

namespace OrderBundle\Repository;

/**
 * OrderAnnulCauseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderAnnulCauseRepository extends \Doctrine\ORM\EntityRepository
{
}
