<?php

namespace OrderBundle\Repository;

/**
 * OrderAnnulItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderAnnulItemRepository extends \Doctrine\ORM\EntityRepository
{
}
