<?php

namespace OrderBundle\Repository;

/**
 * OrderItemStatusLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderItemStatusLogRepository extends \Doctrine\ORM\EntityRepository
{
}
