<?php

namespace OrderBundle\Repository;

/**
 * SalesRegisterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalesRegisterRepository extends \Doctrine\ORM\EntityRepository
{
}
