# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
<<<<<<< HEAD
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:7.1.1

=======
# image: php:7.3.6
>>>>>>> 9c2a6b35329a67ced0aa88b53f2ffb39ac2f69df
pipelines:
  default:
    - step:
        caches:
          - composer
        deployment: test
        script:
<<<<<<< HEAD
#          - apt-get update && apt-get install -y unzip
#          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          # Installing first the libraries necessary to configure and install gd
#          - apt-get update && apt-get install -y libpq-dev libfreetype6-dev libjpeg62-turbo-dev libpng12-dev 
#          - docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql
#          - docker-php-ext-install pdo pdo_pgsql pgsql
          # Now we can configure and install the extension
#          - docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
#         - docker-php-ext-install -j$(nproc) gd
#         - docker-php-ext-install -j$(nproc) zip
#          - docker-php-ext-install -j$(nproc) bcmath
#          - docker-php-ext-install -j$(nproc) sockets
#          - pecl install amqp
#          - docker-php-ext-enable amqp
          - cd vseinet.ru
#          - composer require php-amqplib/php-amqplib
#          - composer install
#          - php bin/console app:config:bus-services
#          - php bin/console generate:api:doc
          #- vendor/bin/phpunit
#          - php vendor/bin/simple-phpunit
=======
          - cd vseinet.ru
  branches:
    master:
      - step:
          name: Test
          deployment: test
          script:
            - pipe: atlassian/ssh-run:0.2.0
              variables:
                SSH_USER: $USER
                SERVER: $SERVER
                COMMAND: 'cd $REMOTE_PATH; git pull origin master; cd vseinet.ru; php72 /usr/local/bin/composer install; php72 bin/console app:config:bus-services; yarn build;'
      - step:
          name: Production
          deployment: production
          script:
            - pipe: atlassian/ssh-run:0.2.0
              variables:
                SSH_USER: $USER
                SERVER: $SERVER
                COMMAND: 'cd $REMOTE_PATH; git pull origin master; cd vseinet.ru; composer install; php bin/console app:config:bus-services; yarn build;'
>>>>>>> 9c2a6b35329a67ced0aa88b53f2ffb39ac2f69df
