<?php

namespace AppBundle\Repository;

/**
 * ApiMethodSubroleCodexRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiMethodSubroleCodexRepository extends \Doctrine\ORM\EntityRepository
{
}
