<?php

namespace AppBundle\Repository;

/**
 * ApiMethodSectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiMethodSectionRepository extends \Doctrine\ORM\EntityRepository
{
}
