<?php

namespace AppBundle\Repository;

/**
 * ApiMethodUserCodexRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiMethodUserCodexRepository extends \Doctrine\ORM\EntityRepository
{
}
