<?php

namespace AppBundle\Repository;

/**
 * ApiMethodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiMethodRepository extends \Doctrine\ORM\EntityRepository
{
}
