<?php

namespace AppBundle\Repository;

/**
 * BannerMainProductDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerMainProductDataRepository extends \Doctrine\ORM\EntityRepository
{
}
