<?php

namespace AppBundle\Repository;

/**
 * BaseProductLastviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseProductLastviewRepository extends \Doctrine\ORM\EntityRepository
{
}
