<?php

namespace AppBundle\Repository;

/**
 * BaseProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseProductRepository extends \Doctrine\ORM\EntityRepository
{
}
