<?php

namespace AppBundle\Repository;

/**
 * BaseProductImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseProductImageRepository extends \Doctrine\ORM\EntityRepository
{
}
