<?php

namespace AppBundle\Repository;

/**
 * BrandByCategoryStatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandByCategoryStatsRepository extends \Doctrine\ORM\EntityRepository
{
}
