<?php

namespace AppBundle\Repository;

/**
 * BrandStatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandStatsRepository extends \Doctrine\ORM\EntityRepository
{
}
