<?php

namespace AppBundle\Repository;

/**
 * BrandPseudoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandPseudoRepository extends \Doctrine\ORM\EntityRepository
{
}
