<?php

namespace AppBundle\Repository;

/**
 * CategorySectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorySectionRepository extends \Doctrine\ORM\EntityRepository
{
}
