<?php

namespace AppBundle\Repository;

/**
 * CategoryPathRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryPathRepository extends \Doctrine\ORM\EntityRepository
{
}
