<?php

namespace AppBundle\Repository;

/**
 * CategorySeoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorySeoRepository extends \Doctrine\ORM\EntityRepository
{
}
