<?php

namespace AppBundle\Repository;

/**
 * CategoryStatsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryStatsRepository extends \Doctrine\ORM\EntityRepository
{
}
