<?php

namespace AppBundle\Repository;

/**
 * CheaperRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CheaperRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
