<?php

namespace AppBundle\Repository;

/**
 * SuggestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientSuggestionRepository extends \Doctrine\ORM\EntityRepository
{
}
