<?php

namespace AppBundle\Repository;

/**
 * ClientOrderItemTrackingRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientOrderItemTrackingRepository extends \Doctrine\ORM\EntityRepository
{
}
