<?php

namespace AppBundle\Repository;

/**
 * CompanyToFinancialCounteragentRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyToFinancialCounteragentRepository extends \Doctrine\ORM\EntityRepository
{
}
