<?php

namespace AppBundle\Repository;

/**
 * CompetitorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetitorRepository extends \Doctrine\ORM\EntityRepository
{
    public function getActive()
    {
        return $this->findBy(['isActive' => true]);
    }

    public function getEditable()
    {
        $competitors = $this->findBy(['isActive' => true, 'channel' => ['retail', 'site']]);
        return array_filter($competitors, function($competitor){
            return 'retail' === $competitor->getChannel() || 'site' === $competitor->getChannel() && 'product' === $competitor->getParseStrategy();
        });
    }
}
