<?php

namespace AppBundle\Repository;

/**
 * CompetitorProductRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetitorProductRepository extends \Doctrine\ORM\EntityRepository
{
}
