<?php

namespace AppBundle\Repository;

/**
 * CompetitorCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetitorCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
