<?php

namespace AppBundle\Repository;

/**
 * ComuserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComuserRepository extends \Doctrine\ORM\EntityRepository
{
}
