<?php

namespace AppBundle\Repository;

/**
 * CounteragentSettlementAccountRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CounteragentSettlementAccountRepository extends \Doctrine\ORM\EntityRepository
{
}
