<?php

namespace AppBundle\Repository;

/**
 * DetailMemoToProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailMemoToProductRepository extends \Doctrine\ORM\EntityRepository
{
}
