<?php

namespace AppBundle\Repository;

/**
 * DetailToProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailToProductRepository extends \Doctrine\ORM\EntityRepository
{
}
