<?php

namespace AppBundle\Repository;

/**
 * DiscountCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscountCodeRepository extends \Doctrine\ORM\EntityRepository
{
}
