<?php

namespace AppBundle\Repository;

/**
 * EmploymentHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmploymentHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
