<?php

namespace AppBundle\Repository;

/**
 * EmployeeToGeoRoomRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeToGeoRoomRepository extends \Doctrine\ORM\EntityRepository
{
}
