<?php

namespace AppBundle\Repository;

/**
 * FinancialCounteragentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinancialCounteragentRepository extends \Doctrine\ORM\EntityRepository
{
}
