<?php

namespace AppBundle\Repository;

/**
 * GeoAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeoAddressRepository extends \Doctrine\ORM\EntityRepository
{
}
