<?php

namespace AppBundle\Repository;

/**
 * OrderItemStatusRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderItemStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
