<?php

namespace AppBundle\Repository;

/**
 * ParserProductRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParserProductRepository extends \Doctrine\ORM\EntityRepository
{
}
