<?php

namespace AppBundle\Repository;

/**
 * ParserDetailValueRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParserDetailValueRepository extends \Doctrine\ORM\EntityRepository
{
}
