<?php

namespace AppBundle\Repository;

/**
 * PartnerProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartnerProductRepository extends \Doctrine\ORM\EntityRepository
{
}
