<?php

namespace AppBundle\Repository;

/**
 * PricetagRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PricetagRepository extends \Doctrine\ORM\EntityRepository
{
}
