<?php

namespace AppBundle\Repository;

/**
 * ProductPricetagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductPricetagRepository extends \Doctrine\ORM\EntityRepository
{
}
