<?php

namespace AppBundle\Repository;

/**
 * ProductTotalSaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductTotalSaleRepository extends \Doctrine\ORM\EntityRepository
{
}
