<?php

namespace AppBundle\Repository;

/**
 * ProductPricetagBufferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductPricetagBufferRepository extends \Doctrine\ORM\EntityRepository
{
}
