<?php

namespace AppBundle\Repository;

/**
 * ProductPricetagSettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductPricetagSettingsRepository extends \Doctrine\ORM\EntityRepository
{
}
