<?php

namespace AppBundle\Repository;

/**
 * ProductToCompetitorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductToCompetitorRepository extends \Doctrine\ORM\EntityRepository
{
}
