<?php

namespace AppBundle\Repository;

/**
 * RepresentativePhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepresentativePhotoRepository extends \Doctrine\ORM\EntityRepository
{
}
