<?php

namespace AppBundle\Repository;

/**
 * RepresentativeScheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepresentativeScheduleRepository extends \Doctrine\ORM\EntityRepository
{
}
