<?php

namespace AppBundle\Repository;

/**
 * RepresentativePhoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepresentativePhoneRepository extends \Doctrine\ORM\EntityRepository
{
}
