<?php

namespace AppBundle\Repository;

/**
 * RepresentativeToPaymentTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepresentativeToPaymentTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
