<?php

namespace AppBundle\Repository;

/**
 * ResourceUserCodexRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourceUserCodexRepository extends \Doctrine\ORM\EntityRepository
{
}
