<?php

namespace AppBundle\Repository;

/**
 * ResourceMethodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourceMethodRepository extends \Doctrine\ORM\EntityRepository
{
}
