<?php

namespace AppBundle\Repository;

/**
 * ResourceSubroleCodexRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourceSubroleCodexRepository extends \Doctrine\ORM\EntityRepository
{
}
