<?php

namespace AppBundle\Repository;

/**
 * SettlementAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettlementAccountRepository extends \Doctrine\ORM\EntityRepository
{
}
