<?php

namespace AppBundle\Repository;

/**
 * SubroleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubroleRepository extends \Doctrine\ORM\EntityRepository
{
}
