<?php

namespace AppBundle\Repository;

/**
 * SubroleCodexRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubroleCodexRepository extends \Doctrine\ORM\EntityRepository
{
}
