<?php

namespace AppBundle\Repository;

/**
 * SupplyItemRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplyItemRepository extends \Doctrine\ORM\EntityRepository
{
}
