<?php

namespace AppBundle\Repository;

/**
 * TradeMarginRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TradeMarginRepository extends \Doctrine\ORM\EntityRepository
{
}
