<?php

namespace AppBundle\Repository;

/**
 * TransportCompanyTerminalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransportCompanyTerminalRepository extends \Doctrine\ORM\EntityRepository
{
}
