<?php

namespace AppBundle\Repository;

/**
 * UserToAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserToAddressRepository extends \Doctrine\ORM\EntityRepository
{
}
