<?php

namespace AppBundle\Repository;

/**
 * UserToSubroleRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserToSubroleRepository extends \Doctrine\ORM\EntityRepository
{
}
