<?php

namespace AppBundle\Repository;

/**
 * UserCodexRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCodexRepository extends \Doctrine\ORM\EntityRepository
{
}
