<?php

namespace AppBundle\Repository;

/**
 * ViewHistoryBrandRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViewHistoryBrandRepository extends \Doctrine\ORM\EntityRepository
{
}
