<?php

namespace AppBundle\Repository;

/**
 * ViewUserPersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViewUserPersonRepository extends \Doctrine\ORM\EntityRepository
{
}
