<?php

namespace AppBundle\Repository;

/**
 * WholesaleContractRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WholesaleContractRepository extends \Doctrine\ORM\EntityRepository
{
}
