<?php

namespace OrgBundle\Repository;

/**
 * ActivityHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
