<?php

namespace OrgBundle\Repository;

/**
 * ActivityObjectToIndexRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityObjectToIndexRepository extends \Doctrine\ORM\EntityRepository
{
}
