<?php

namespace OrgBundle\Repository;

/**
 * ActivityObjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityObjectRepository extends \Doctrine\ORM\EntityRepository
{
}
