<?php

namespace OrgBundle\Repository;

/**
 * ActivityAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityAreaRepository extends \Doctrine\ORM\EntityRepository
{
}
