<?php

namespace OrgBundle\Repository;

/**
 * ActivityIndexRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityIndexRepository extends \Doctrine\ORM\EntityRepository
{
}
