<?php

namespace OrgBundle\Repository;

/**
 * ActivityObjectToAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityObjectToAreaRepository extends \Doctrine\ORM\EntityRepository
{
}
