<?php

namespace OrgBundle\Repository;

/**
 * CashDeskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CashDeskRepository extends \Doctrine\ORM\EntityRepository
{
}
