<?php

namespace OrgBundle\Repository;

/**
 * ClientSuggestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientSuggestionRepository extends \Doctrine\ORM\EntityRepository
{
}
