<?php

namespace OrgBundle\Repository;

/**
 * ClientSuggestionCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientSuggestionCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
