<?php

namespace OrgBundle\Repository;

/**
 * ComplaintCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComplaintCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
