<?php

namespace OrgBundle\Repository;

/**
 * DepartmentTypeEmployeeActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartmentTypeEmployeeActivityRepository extends \Doctrine\ORM\EntityRepository
{
}
