<?php

namespace OrgBundle\Repository;

/**
 * DepartmentTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartmentTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
