<?php

namespace OrgBundle\Repository;

/**
 * DepartmentToDepartmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartmentToDepartmentRepository extends \Doctrine\ORM\EntityRepository
{
}
