<?php

namespace OrgBundle\Repository;

/**
 * DepartmentPathRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartmentPathRepository extends \Doctrine\ORM\EntityRepository
{
}
