<?php

namespace OrgBundle\Repository;

/**
 * EmployeeScheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeScheduleRepository extends \Doctrine\ORM\EntityRepository
{
}
