<?php

namespace OrgBundle\Repository;

/**
 * EmployeeToDocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeToDocumentRepository extends \Doctrine\ORM\EntityRepository
{
}
