<?php

namespace OrgBundle\Repository;

/**
 * EmployeeFineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeFineRepository extends \Doctrine\ORM\EntityRepository
{
}
