<?php

namespace OrgBundle\Repository;

/**
 * EmployeeDocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeDocumentRepository extends \Doctrine\ORM\EntityRepository
{
}
