<?php

namespace OrgBundle\Repository;

/**
 * EmployeeToCashDeskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeToCashDeskRepository extends \Doctrine\ORM\EntityRepository
{
}
