<?php

namespace OrgBundle\Repository;

/**
 * EmployeeToDepartmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeToDepartmentRepository extends \Doctrine\ORM\EntityRepository
{
}
