<?php

namespace OrgBundle\Repository;

/**
 * EmployeeRelativeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeRelativeRepository extends \Doctrine\ORM\EntityRepository
{
}
