<?php

namespace OrgBundle\Repository;

/**
 * EmployeeWageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeWageRepository extends \Doctrine\ORM\EntityRepository
{
}
