<?php

namespace OrgBundle\Repository;

/**
 * EmployeeTaxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeTaxRepository extends \Doctrine\ORM\EntityRepository
{
}
