<?php

namespace OrgBundle\Repository;

/**
 * EmployeeAttendanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeAttendanceRepository extends \Doctrine\ORM\EntityRepository
{
}
