<?php

namespace OrgBundle\Repository;

/**
 * EmployeeSalaryActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeSalaryActivityRepository extends \Doctrine\ORM\EntityRepository
{
}
