<?php

namespace OrgBundle\Repository;

/**
 * EmployeeCancelRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeCancelRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
