<?php

namespace OrgBundle\Repository;

/**
 * GeoRoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeoRoomRepository extends \Doctrine\ORM\EntityRepository
{
}
