<?php

namespace OrgBundle\Repository;

/**
 * OrgContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrgContactRepository extends \Doctrine\ORM\EntityRepository
{
}
