<?php

namespace OrgBundle\Repository;

/**
 * OrgEmployeeExtraFeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrgEmployeeExtraFeeRepository extends \Doctrine\ORM\EntityRepository
{
}
