<?php

namespace OrgBundle\Repository;

/**
 * RepresentativeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepresentativeRepository extends \Doctrine\ORM\EntityRepository
{
}
