<?php

namespace OrgBundle\Repository;

/**
 * SalaryPlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalaryPlanRepository extends \Doctrine\ORM\EntityRepository
{
}
