<?php

namespace OrgBundle\Repository;

/**
 * SalaryPaymentLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalaryPaymentLogRepository extends \Doctrine\ORM\EntityRepository
{
}
