<?php

namespace OrgBundle\Repository;

/**
 * SalaryComponentVariantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalaryComponentVariantRepository extends \Doctrine\ORM\EntityRepository
{
}
