<?php

namespace OrgBundle\Repository;

/**
 * SalaryComponentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalaryComponentRepository extends \Doctrine\ORM\EntityRepository
{
}
