<?php

namespace OrgBundle\Repository;

/**
 * SalaryIndexRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalaryIndexRepository extends \Doctrine\ORM\EntityRepository
{
}
