<?php

namespace OrgBundle\Repository;

/**
 * SalaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalaryRepository extends \Doctrine\ORM\EntityRepository
{
}
