<?php

namespace SiteBundle\Repository;

/**
 * ContentPageCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentPageCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
