<?php

namespace GeoBundle\Repository;

/**
 * GeoAddressToPersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeoAddressToPersonRepository extends \Doctrine\ORM\EntityRepository
{
}
