<?php

namespace GeoBundle\Repository;

/**
 * GeoIpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeoIpRepository extends \Doctrine\ORM\EntityRepository
{
}
