<?php

namespace GeoBundle\Repository;

/**
 * GeoPointRouteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeoPointRouteRepository extends \Doctrine\ORM\EntityRepository
{
}
