<?php

namespace PricingBundle\Repository;

/**
 * ProductPriceLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductPriceLogRepository extends \Doctrine\ORM\EntityRepository
{
}
