<?php

namespace AccountingBundle\Repository;

/**
 * BankCardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BankCardRepository extends \Doctrine\ORM\EntityRepository
{
}
