<?php

namespace AccountingBundle\Repository;

/**
 * CounteragentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CounteragentRepository extends \Doctrine\ORM\EntityRepository
{
}
