<?php

namespace AccountingBundle\Repository;

/**
 * EWalletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EWalletRepository extends \Doctrine\ORM\EntityRepository
{
}
