<?php

namespace AccountingBundle\Repository;

/**
 * FinancialResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinancialResourceRepository extends \Doctrine\ORM\EntityRepository
{
}
