<?php

namespace AccountingBundle\Repository;

/**
 * OneCSupplyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OneCSupplyRepository extends \Doctrine\ORM\EntityRepository
{
}
