<?php

namespace AccountingBundle\Repository;

/**
 * OurSellerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OurSellerRepository extends \Doctrine\ORM\EntityRepository
{
}
