services:
    profiler.listener:
        class: 'AdminBundle\EventListener\ProfilerListener'
        public: true
        arguments: [ '@profiler' ]
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest', priority: 64 }