# https://symfony.com/blog/new-in-symfony-3-4-services-are-private-by-default
services:
    command_bus:
        alias: simple_bus.command_bus
        public: true

    query_bus:
        alias: simple_bus.query_bus
        public: true

    command_bus.middleware.validation:
        class: AppBundle\Bus\Middleware\CommandValidationMiddleware
        public: false
        arguments: [ '@validator' ]
        tags: 
            - { name: command_bus_middleware }
            
    query_bus.middleware.validation:
        class: AppBundle\Bus\Middleware\QueryValidationMiddleware
        public: false
        arguments: [ '@validator' ]
        tags: 
            - { name: query_bus_middleware }
