services:
    tactician.middleware.param_fetcher:
        class: AppBundle\Bus\Middleware\ParamFetcherMiddleware
        public: false
        arguments: [ '@annotation_reader' ]

    tactician.middleware.validation:
        class: AppBundle\Bus\Middleware\ValidationMiddleware
        public: false
        arguments: [ '@validator' ]

    tactician.middleware.transaction:
        class: AppBundle\Bus\Middleware\TransactionMiddleware
        public: false
        arguments: [ '@doctrine.orm.entity_manager' ]

    command_bus:
        alias: tactician.commandbus
        public: true

    query_bus:
        alias: tactician.commandbus.query
        public: true

tactician:
    commandbus:
        default:
            middleware:
                - tactician.middleware.param_fetcher
                - tactician.middleware.validation
                - tactician.middleware.transaction
                - tactician.middleware.command_handler
        query:
            middleware:
                - tactician.middleware.param_fetcher
                - tactician.middleware.validation
                - tactician.commandbus.query.middleware.command_handler