services:
    catalog.category_product.finder:
        class: 'AppBundle\Bus\Catalog\Finder\CategoryProductFinder'
        public: true
        calls:
            - [ 'setContainer', [ '@service_container' ] ]

    catalog.special_product.finder:
        class: 'AppBundle\Bus\Catalog\Finder\SpecialProductFinder'
        public: true
        calls:
            - [ 'setContainer', [ '@service_container' ] ]

    catalog.total_sale_product.finder:
        class: 'AppBundle\Bus\Catalog\Finder\TotalSaleProductFinder'
        public: true
        calls:
            - [ 'setContainer', [ '@service_container' ] ]

    catalog.search_product.finder:
        class: 'AppBundle\Bus\Catalog\Finder\SearchProductFinder'
        public: true
        calls:
            - [ 'setContainer', [ '@service_container' ] ]

    catalog.brand_product.finder:
        class: 'AppBundle\Bus\Catalog\Finder\BrandProductFinder'
        public: true
        calls:
            - [ 'setContainer', [ '@service_container' ] ]

    catalog.detail_product.finder:
        class: 'AppBundle\Bus\Catalog\Finder\DetailProductFinder'
        public: true
        calls:
            - [ 'setContainer', [ '@service_container' ] ]

    catalog.detail_value_product.finder:
        class: 'AppBundle\Bus\Catalog\Finder\DetailValueProductFinder'
        public: true
        calls:
            - [ 'setContainer', [ '@service_container' ] ]

    catalog.supplier_product.finder:
        class: 'AppBundle\Bus\Catalog\Finder\SupplierProductFinder'
        public: true
        calls:
            - [ 'setContainer', [ '@service_container' ] ]

    catalog.autocomplete.finder:
        class: 'AppBundle\Bus\Catalog\Finder\AutocompleteFinder'
        public: true
        calls:
            - [ 'setContainer', [ '@service_container' ] ]

    catalog.product.finder.filter:
        class: 'AppBundle\Bus\Catalog\Finder\Filter'
        public: true
        calls:
            - [ 'setContainer',[ '@service_container' ] ]

    catalog.product.finder.query_builder:
        class: 'AppBundle\Bus\Catalog\Finder\QueryBuilder'
        public: true
        calls:
            - [ 'setContainer', [ '@service_container' ] ]

