imports:
    - { resource: admin.yml }
    - { resource: config.yml }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: notice
            max_files: 10
        console:
            type: console
            process_psr_3_messages: false
