imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: bus.yml }
    - { resource: bus-services.yml, ignore_errors: true }
    - { resource: uploads.yml }
    - { resource: rabbitmq.yml }
    - { resource: doctrine.yml }
    - { resource: constants.yml }
    - { resource: monolog.yml }
    - { resource: twig.yml }
    - { resource: sphinx.yml }
    - { resource: parsers.yml }
    - { resource: "@GeoBundle/Resources/config/services.yml" }
    - { resource: "@SiteBundle/Resources/config/services.yml" }
    
    - { resource: "@ContentBundle/Resources/config/services.yml" }
    # - { resource: "@ThirdPartyBundle/Resources/config/services.yml" }
    # - { resource: "@ServiceBundle/Resources/config/services.yml" }
    - { resource: "@OrgBundle/Resources/config/services.yml" }
    # - { resource: "@OrderBundle/Resources/config/services.yml" }
    - { resource: "@PricingBundle/Resources/config/services.yml" }
    # - { resource: "@OrderBundle/Resources/config/services.yml" }
    # - { resource: "@AccountingBundle/Resources/config/services.yml" }
    # - { resource: "@ClaimsBundle/Resources/config/services.yml" }
    # - { resource: "@ReservesBundle/Resources/config/services.yml" }
    # - { resource: "@DocumentBundle/Resources/config/services.yml" }
    # - { resource: "@FinanseBundle/Resources/config/services.yml" }
    # - { resource: "@RegisterBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    jms_serializer.camel_case_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy

framework:
    #esi: ~
    translator: 
        enabled: false
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    # serializer: { enable_annotations: true }
    templating:
        engines: [ 'twig' ]
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_secure: '%cookie_secure%'
    fragments: ~
    http_method_override: true
    assets: 
        json_manifest_path: '%kernel.project_dir%/web/bundles/manifest.json'
    php_errors:
        log: true


# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# FOS Rest Configuration
# fos_rest:
#     body_listener:
#         array_normalizer: fos_rest.normalizer.camel_keys
#     body_converter:
#         enabled: true
#     format_listener:
#         rules:
#             - { path: ^/(user|api/v|api/(spec|routes)), priorities: [ 'json' ], fallback_format: json, prefer_extension: false }
#             - { path: ^/, priorities: [ 'html' ], fallback_format: json, prefer_extension: false }
#     # param_fetcher_listener: true
#     # serializer:
#         # serialize_null: true
#     view:
#         view_response_listener: force
#         formats:
#             json: true
    # exception:
        # enabled: true
        # exception_controller: 'AppBundle\Controller\ExceptionController::showAction'

# FOS OAuthServer Configuration
# fos_oauth_server:
#     db_driver: orm       
#     client_class: AppBundle\Entity\Client
#     access_token_class: AppBundle\Entity\AccessToken
#     refresh_token_class: AppBundle\Entity\RefreshToken
#     auth_code_class: AppBundle\Entity\AuthCode
#     service:
#         user_provider: user.provider

fos_js_routing:
    routes_to_expose: [ 'login$', catalog_category$', 'catalog_product$', 'catalog_search_autocomplete$' ]