services:
    geo_city.form:
        class: 'AppBundle\Bus\Geo\Form\GeoCityType'
        public: false
        arguments: [ '@doctrine.orm.entity_manager' ]
        tags:
            - { name: 'form.type' }

    is_human.form:
        class: 'AppBundle\Bus\User\Form\IsHumanType'
        public: false
        arguments: [ '@security.token_storage' ]
        tags:
            - { name: 'form.type' }

    cheaper_request.form:
        class: 'AppBundle\Bus\Main\Form\CheaperRequestType'
        public: false
        arguments: [ '@doctrine.orm.entity_manager' ]
        tags:
            - { name: 'form.type' }

    complaint.form:
        class: 'AppBundle\Bus\Main\Form\ComplaintFormType'
        public: false 
        arguments: [ '@doctrine.orm.entity_manager' ]
        tags:
            - { name: 'form.type' }
