httplug:
    plugins:
        logger: ~
    clients:
        guzzle:
            factory: 'httplug.factory.guzzle6'
            plugins: [ 'httplug.plugin.logger' ]
            config:
                timeout: 30