fos_js_routing:
    routes_to_expose:
        - 'login$'
        - 'catalog_category$'
        - 'catalog_product$'
        - 'catalog_search_autocomplete'
        - 'user_search_autocomplete'
        - 'geo_cities'
        - 'select_geo_region'
        - 'select_geo_city'
        - 'search_geo_city'
        - 'search_geo_street'
        - 'error_report'
        - 'order_status'
        - 'cart_set_quantity'
        - 'admin_*'
        # - 'admin_product_merge'
        # - 'admin_product_move'
        # - 'admin_categories'
        # - 'admin_search_categories'
        # - 'admin_supplier_remains'
        # - 'admin_supplier_unlink'
        # - 'admin_supplier_restore'
