fos_js_routing:
    routes_to_expose:
        - 'login$'
        - 'catalog_category$'
        - 'catalog_product$'
        - 'catalog_search_autocomplete'
        - 'user_search_autocomplete'
        - 'order_created_page'
        - 'authority'
        - 'geo_cities'
        - 'select_geo_region'
        - 'select_geo_city'
        - 'search_geo_city'
        - 'search_geo_street'
        - 'get_bank'
        - 'error_report'
        - 'order_status'
        - 'cart_set_quantity'
        - 'product_get_price'
        - 'admin_*'
