old_sound_rabbit_mq:
    connections:
        default:
            host: '%rabbit_host%'
            port: '%rabbit_port%'
            user: '%rabbit_user%'
            password: '%rabbit_password%'
            vhost:    '/'
            lazy:     false
            connection_timeout: 3
            read_write_timeout: 3
            keepalive: false
            heartbeat: 0
            use_socket: true 
    producers:
        resize.image:
            connection: default
            exchange_options: { name: 'resize.image', type: direct }
            queue_options: { name: 'resize.image' }
        execute.command:
            connection: default
            exchange_options: { name: 'execute.command', type: 'direct' }
            queue_options: { name: 'execute.command' }
        notify.front:
            connection: default
            exchange_options: { name: 'notify.front', type: 'direct' }
            queue_options: { name: 'notify.front' }

        # bridge to old site
        execute.script:
            connection: default
            exchange_options: { name: 'execute.script', type: 'direct' }
            queue_options: { name: 'execute.script' }
