fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

site:
    resource: "@SiteBundle/Controller/"
    type:     annotation
    prefix:   /

geo:
    resource: "@GeoBundle/Controller/"
    type:     annotation
    prefix:   /

register:
    resource: "@RegisterBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type: annotation
    prefix: /


