<<<<<<< HEAD
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

site:
    resource: "@SiteBundle/Controller/"
    type:     annotation
    prefix:   /

geo:
    resource: "@GeoBundle/Controller/"
    type:     annotation
    prefix:   /

register:
    resource: "@RegisterBundle/Controller/"
    type:     annotation
    prefix:   /

=======
>>>>>>> 958dfbdf55ccea6307e187445d24ce3c38b34adf
app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
