_wdt:
    resource: '@WebProfilerBundle/Resources/config/routing/wdt.xml'
    prefix: /_wdt

_profiler:
    resource: '@WebProfilerBundle/Resources/config/routing/profiler.xml'
    prefix: /_profiler

admin:
    resource: '@AdminBundle/Controller/'
    type: annotation

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_js_routing:
    resource: '@FOSJsRoutingBundle/Resources/config/routing/routing.xml'
