# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User: 
            algorithm: bcrypt 
            cost: 4

    providers:
        user.provider:
            id: user.provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login: 
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
                use_referer: true
            remember_me: 
                secret: lksjfcmxzn
            logout_on_user_change: true
            logout:
                path: /logout
                target: /
                invalidate_session: true
                delete_cookies: ~

    access_control:
        - { path: ^/admin, roles: IS_AUTHENTICATED_FULLY }

