# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User: 
            algorithm: bcrypt 
            cost: 4

    providers:
        user.provider:
            id: user.provider
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        app:
            pattern: ^/
            anonymous: ~
            logout_on_user_change: true


    # access_control:
        # - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/forgot, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/logout, roles: [ IS_AUTHENTICATED_FULLY ] }
