services:
    user.provider:
        class: 'AppBundle\Security\UserProvider'
        public: false
        arguments: [ '@doctrine.orm.entity_manager' ]

    security.authentication.rememberme.services.simplehash: 
        class: 'AppBundle\Security\RememberMeServices'
        parent: 'security.authentication.rememberme.services.abstract'
        public: false 
        abstract: true

    session.storage.native:
        class: 'AppBundle\Session\NativeSessionStorage'
        arguments: [ '%session.storage.options%', '@session.handler', '@session.storage.metadata_bag' ]
        public: true    

    app.security.authentication_handler:
        class: 'AppBundle\Security\AuthenticationHandler'
        public: false
        arguments: [ '@router', '@session' ]

    api.client:
        class: 'AppBundle\Security\ApiClient'
        arguments: [ '%api.host%', '%api.public_id%', '%api.secret%', '@session', '@httplug.message_factory', '@httplug.client.guzzle' ]
        public: true

    geo_city.identity:
        class: 'AppBundle\Service\GeoCityIdentity'
        public: true
        calls:
            - [ 'setContainer', [ '@service_container' ] ]

    representative.identity:
        class: 'AppBundle\Service\RepresentativeIdentity'
        public: true
        calls:
            - [ 'setContainer', [ '@service_container' ] ]

    delivery.date:
        class: 'AppBundle\Service\DeliveryDate'
        public: true 
        calls:
            - [ 'setContainer', [ '@service_container' ] ]

    phone.formatter:
        class: 'AppBundle\Service\PhoneFormatter'
        public: true 

    address.formatter:
        class: 'AppBundle\Service\AddressFormatter'
        public: true 
        arguments: [ '@doctrine.orm.entity_manager' ]
