parameters:
    sphinx.conf.path: '%kernel.project_dir%/bin/sphinx/config/sphinx.conf'

services:
    sphinxql:
        class: AppBundle\SphinxQL\SphinxQL
        public: true
        arguments: [ '%sphinxql_host%', '%sphinxql_port%' ]