parameters:
    sphinx.conf.path: '%kernel.project_dir%/bin/sphinx/pgsql/dev.conf'
    sphinx.indexer.path: '%kernel.project_dir%/bin/sphinx/pgsql/indexer.js'

services:
    sphinxql:
        class: AppBundle\SphinxQL\SphinxQL
        public: true
        arguments: [ '%sphinxql_host%', '%sphinxql_port%' ]