services:
    twig.extension.price_format:
        class: 'AppBundle\Twig\Extension\PriceFormatExtension'
        tags:
            - { name: 'twig.extension' }

    twig.extension.declension:
        class: 'AppBundle\Twig\Extension\DeclensionExtension'
        tags:
            - { name: 'twig.extension' }

    twig.extension.url_decode:
        class: 'AppBundle\Twig\Extension\UrlDecoderExtension'
        tags:
            - { name: 'twig.extension' }

    twig.extension.phone_format:
        class: 'AppBundle\Twig\Extension\PhoneFormatExtension'
        arguments: [ '@phone.formatter' ]
        tags:
            - { name: 'twig.extension' }

    twig.extension.image:
        class: 'AppBundle\Twig\Extension\ImageExtension'
        arguments: [ '%images.path%' ]
        tags:
            - { name: 'twig.extension' }

    twig.extension.discount:
        class: 'AppBundle\Twig\Extension\DiscountExtension'
        tags:
            - { name: 'twig.extension' }

    twig.extension.autocut:
        class: 'AppBundle\Twig\Extension\AutocutExtension'
        tags:
            - { name: 'twig.extension' }

    app.twig.globals:
        class: 'AppBundle\Twig\GlobalVariables'
        arguments: [ '@service_container' ]

twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        app: '@app.twig.globals'

    number_format:
        decimals: 0
        decimal_point: ','
        thousands_separator: ' '