services:
    twig.extension.price_format:
        class: 'AppBundle\Twig\Extension\PriceFormatExtension'
        tags:
            - { name: 'twig.extension' }

    twig.extension.declension:
        class: 'AppBundle\Twig\Extension\DeclensionExtension'
        tags:
            - { name: 'twig.extension' }

    twig.extension.url_decode:
        class: 'AppBundle\Twig\Extension\UrlDecoderExtension'
        tags:
            - { name: 'twig.extension' }

    twig.extension.phone_format:
        class: 'AppBundle\Twig\Extension\PhoneFormatExtension'
        arguments: [ '@phone.formatter' ]
        tags:
            - { name: 'twig.extension' }

    twig.extension.image:
        class: 'AppBundle\Twig\Extension\ImageExtension'
        arguments: [ '%images.path%' ]
        tags:
            - { name: 'twig.extension' }

    twig.extension.discount:
        class: 'AppBundle\Twig\Extension\DiscountExtension'
        tags:
            - { name: 'twig.extension' }

    twig.extension.autocut:
        class: 'AppBundle\Twig\Extension\AutocutExtension'
        tags:
            - { name: 'twig.extension' }

    twig.extension.external_link:
        class: 'AppBundle\Twig\Extension\ExternalLinkExtension'
        tags:
            - { name: 'twig.extension' }

    twig.extension.date_format:
        class: 'AppBundle\Twig\Extension\DateFormatExtension'
        tags:
            - { name: 'twig.extension' }

    app.twig.globals:
        class: 'AppBundle\Twig\GlobalVariables'
        arguments: [ '@service_container' ]

twig:
    exception_controller: exception.controller:showAction
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        app: '@app.twig.globals'
        credit_threshold: '%const.payment.credit.threshold%'
        post_delivery_cost: '%const.delivery.post.cost%'
        transport_company_delivery_cost: '%const.delivery.transport_company.cost%'
        admin_host: '%admin.host%'
    paths:
        '%kernel.project_dir%/app/Resources/TwigBundle/views': ~

    number_format:
        decimals: 0
        decimal_point: ','
        thousands_separator: ' '
