parameters:
    supplier.pricelist.web.path: '/u/suppliers/pricelists/'
    supplier.pricelist.path: '%kernel.project_dir%/web%supplier.pricelist.web.path%'

    competitors.export.path: '%kernel.project_dir%/web/u/competitors/export'

    product.images.path: '%kernel.project_dir%/web/u/products'
    product.images.web.path: 'https://cdn.vseinet.ru/products'
    product.images.sizes: [ 800, 280, 200, 100, 60 ]

    brand.logo.path: '%kernel.project_dir%/web/u/brands'

    project.web.path: '%kernel.project_dir%/web'
    project.web.images.path: '%project.web.path%/images'
    project.web.contacts.path: '%project.web.path%/u/contacts'
    pdf.documents.orders.invoices.path: '%project.web.path%/u/documents/orders/invoices'
    pdf.documents.orders.commercials.path: '%project.web.path%/u/documents/orders/commercials'
    pdf.documents.orders.contracts.path: '%project.web.path%/u/documents/orders/contracts'
    pdf.documents.orders.order.path: '%project.web.path%/u/documents/orders/order'
    pdf.documents.inventories.path: '%project.web.path%/u/documents/inventories'
    pdf.qrcodes.path: '%project.web.path%/u/qrcodes'

    banner.images.path: '%kernel.project_dir%/web/u/banners/main'
    banner.images.web.path: '/u/banners/main'