<?php

namespace ShopBundle\Repository;

/**
 * BannerMainDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerMainDataRepository extends \Doctrine\ORM\EntityRepository
{
}
