<?php

namespace ShopBundle\Repository;

/**
 * BannerMainBackgroundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerMainBackgroundRepository extends \Doctrine\ORM\EntityRepository
{
}
