<?php

namespace ShopBundle\Repository;

/**
 * BannerMainTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerMainTemplateRepository extends \Doctrine\ORM\EntityRepository
{
}
