<?php

namespace ClaimsBundle\Repository;

/**
 * GoodsIssueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodsIssueRepository extends \Doctrine\ORM\EntityRepository
{
}
