<?php

namespace ClaimsBundle\Repository;

/**
 * GoodsIssueCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodsIssueCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
