<?php

namespace ClaimsBundle\Repository;

/**
 * GoodsIssueTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodsIssueTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
