<?php

namespace RegisterBundle\Repository;

/**
 * GoodsNeedRegisterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodsNeedRegisterRepository extends \Doctrine\ORM\EntityRepository
{
}
