<?php

namespace RegisterBundle\Repository;

/**
 * GoodsReserveRegisterCurrentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodsReserveRegisterCurrentRepository extends \Doctrine\ORM\EntityRepository
{
}
