<?php

namespace RegisterBundle\Repository;

/**
 * GoodsReserveRegisterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodsReserveRegisterRepository extends \Doctrine\ORM\EntityRepository
{
}
