<?php

namespace SupplyBundle\Repository;

/**
 * SupplierEmployeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierEmployeeRepository extends \Doctrine\ORM\EntityRepository
{
}
