<?php

namespace SupplyBundle\Repository;

/**
 * SupplierReserveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierReserveRepository extends \Doctrine\ORM\EntityRepository
{
}
