<?php

namespace SupplyBundle\Repository;

/**
 * SupplierToCounteragentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierToCounteragentRepository extends \Doctrine\ORM\EntityRepository
{
}
