<?php

namespace SupplyBundle\Repository;

/**
 * SupplierInvoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierInvoiceRepository extends \Doctrine\ORM\EntityRepository
{
}
