<?php

namespace SupplyBundle\Repository;

/**
 * SupplierPricelistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierPricelistRepository extends \Doctrine\ORM\EntityRepository
{

}
