<?php

namespace SupplyBundle\Repository;

/**
 * SupplierProductBarCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierProductBarCodeRepository extends \Doctrine\ORM\EntityRepository
{
}
