<?php

namespace SupplyBundle\Repository;

/**
 * SupplierInvoiceItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierInvoiceItemRepository extends \Doctrine\ORM\EntityRepository
{
}
