<?php

namespace SupplyBundle\Repository;

/**
 * SupplierCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
