<?php

namespace SupplyBundle\Repository;

/**
 * SupplierOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
