<?php

namespace SupplyBundle\Repository;

/**
 * SupplierReserveRegisterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierReserveRegisterRepository extends \Doctrine\ORM\EntityRepository
{
}
