<?php

namespace SupplyBundle\Repository;

/**
 * SupplierProductTransferLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierProductTransferLogRepository extends \Doctrine\ORM\EntityRepository
{
}
