<?php

namespace SupplyBundle\Repository;

/**
 * SupplierReserveItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierReserveItemRepository extends \Doctrine\ORM\EntityRepository
{
}
