<?php

namespace SupplyBundle\Repository;

/**
 * SupplierReserveChangeItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierReserveChangeItemRepository extends \Doctrine\ORM\EntityRepository
{
}
