<?php

namespace SupplyBundle\Repository;

/**
 * SupplierCategoryPathRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierCategoryPathRepository extends \Doctrine\ORM\EntityRepository
{
}
