<?php

namespace SupplyBundle\Repository;

/**
 * SupplierReserveChangeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierReserveChangeRepository extends \Doctrine\ORM\EntityRepository
{
}
