<?php

namespace SupplyBundle\Repository;

/**
 * ViewGeoPointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViewGeoPointRepository extends \Doctrine\ORM\EntityRepository
{
}
