<?php

namespace SupplyBundle\Repository;

/**
 * ViewShipmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViewShipmentRepository extends \Doctrine\ORM\EntityRepository
{
}
