<?php

namespace SupplyBundle\Repository;

/**
 * ViewSupplyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViewSupplyRepository extends \Doctrine\ORM\EntityRepository
{
}
