services:
#    document.example:
#        class: DocumentBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    document.status:
        class: DocumentBundle\Service\AnyDocStatus
        public: true
        arguments: [ '@doctrine.orm.entity_manager']
        
    document.number:
        class: DocumentBundle\Service\AnyDocNumber
        public: true
        arguments: [ '@doctrine.orm.entity_manager']
