<?php

namespace DeliveryBundle\Repository;

/**
 * DeliveryItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryItemRepository extends \Doctrine\ORM\EntityRepository
{
}
