<?php

namespace DeliveryBundle\Repository;

/**
 * DeliveryDocRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryDocRepository extends \Doctrine\ORM\EntityRepository
{
}
