<?php

namespace DeliveryBundle\Repository;

/**
 * OrderDeliveryItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderDeliveryItemRepository extends \Doctrine\ORM\EntityRepository
{
}
