<?php

namespace DeliveryBundle\Repository;

/**
 * TransportCompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransportCompanyRepository extends \Doctrine\ORM\EntityRepository
{
}
