services:
    service.sender:
          class: ServiceBundle\Services\SenderService
          public: true
          calls:
              - [ setContainer, [ '@service_container' ] ]
    service.route:
          class: ServiceBundle\Services\RouteService
          public: true
          calls:
              - [ setContainer, [ '@service_container' ] ]
    service.reserve:
          class: ServiceBundle\Services\ReserveService
          public: true
          calls:
              - [ setContainer, [ '@service_container' ] ]
    service.product:
          class: ServiceBundle\Services\ProductService
          public: true
          calls:
              - [ setContainer, [ '@service_container' ] ]
    service.order:
          class: ServiceBundle\Services\OrderService
          public: true
          calls:
              - [ setContainer, [ '@service_container' ] ]
    service.goodsRequest:
          class: ServiceBundle\Services\GoodsRequestService
          public: true
          calls:
              - [ setContainer, [ '@service_container' ] ]
    service.register:
          class: ServiceBundle\Services\RegisterService
          public: true
          calls:
              - [ setContainer, [ '@service_container' ] ]
    service.pdf:
          class: ServiceBundle\Services\PdfService
          public: true
          calls:
              - [ setContainer, [ '@service_container' ] ]
