<?php

namespace ServiceBundle\Repository;

/**
 * NotificationLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationLogRepository extends \Doctrine\ORM\EntityRepository
{
}
