<?php

namespace ServiceBundle\Repository;

/**
 * OrderDocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderDocumentRepository extends \Doctrine\ORM\EntityRepository
{
}
