<?php

namespace ServiceBundle\Repository;

/**
 * ProductUpdateQueueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductUpdateQueueRepository extends \Doctrine\ORM\EntityRepository
{
}
