<?php

namespace ReservesBundle\Repository;

/**
 * AvailableGoodsReservationItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvailableGoodsReservationItemRepository extends \Doctrine\ORM\EntityRepository
{
}
