<?php

namespace ReservesBundle\Repository;

/**
 * AvailableGoodsReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvailableGoodsReservationRepository extends \Doctrine\ORM\EntityRepository
{
}
