<?php

namespace ReservesBundle\Repository;

/**
 * GoodsIssueDocTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodsIssueDocTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
