<?php

namespace ReservesBundle\Repository;

/**
 * GoodsAcceptanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodsAcceptanceRepository extends \Doctrine\ORM\EntityRepository
{
}
