<?php

namespace ReservesBundle\Repository;

/**
 * GoodsIssueDocProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodsIssueDocProductRepository extends \Doctrine\ORM\EntityRepository
{
}
