<?php

namespace ReservesBundle\Repository;

/**
 * GoodsAcceptanceItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodsAcceptanceItemRepository extends \Doctrine\ORM\EntityRepository
{
}
