<?php

namespace ReservesBundle\Repository;

/**
 * GoodsPackagingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodsPackagingRepository extends \Doctrine\ORM\EntityRepository
{
}
