<?php

namespace ReservesBundle\Repository;

/**
 * GoodsIssueLocationRegisterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodsIssueLocationRegisterRepository extends \Doctrine\ORM\EntityRepository
{
}
