<?php

namespace ReservesBundle\Repository;

/**
 * GoodsPackagingItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodsPackagingItemRepository extends \Doctrine\ORM\EntityRepository
{
}
