<?php

namespace ReservesBundle\Repository;

/**
 * GoodsIssueDoc
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodsIssueDocRepository extends \Doctrine\ORM\EntityRepository
{
}
