<?php

namespace ReservesBundle\Repository;

/**
 * GoodsIssueRegisterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodsIssueRegisterRepository extends \Doctrine\ORM\EntityRepository
{
}
