<?php

namespace ReservesBundle\Repository;

/**
 * GoodsRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodsRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
