<?php

namespace ReservesBundle\Repository;

/**
 * GoodsPalletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodsPalletRepository extends \Doctrine\ORM\EntityRepository
{
}
