<?php

namespace ReservesBundle\Repository;

/**
 * GoodsDecisionDocTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodsDecisionDocTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
