<?php

namespace ReservesBundle\Repository;

/**
 * GoodsDecisionDoc
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodsDecisionDocRepository extends \Doctrine\ORM\EntityRepository
{
}
