<?php

namespace ReservesBundle\Repository;

/**
 * InventoryProductCounterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventoryProductCounterRepository extends \Doctrine\ORM\EntityRepository
{
}
