<?php

namespace ReservesBundle\Repository;

/**
 * InventoryProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventoryProductRepository extends \Doctrine\ORM\EntityRepository
{
}
