<?php

namespace ReservesBundle\Repository;

/**
 * InventoryParticipantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventoryParticipantRepository extends \Doctrine\ORM\EntityRepository
{
}
