<?php

namespace ReservesBundle\Repository;

/**
 * SupplyItemToGeoRoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplyItemToGeoRoomRepository extends \Doctrine\ORM\EntityRepository
{
}
