<?php

namespace ReservesBundle\Repository;

/**
 * TradeMatrixTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TradeMatrixTemplateRepository extends \Doctrine\ORM\EntityRepository
{
}
