<?php

namespace ReservesBundle\Repository;

/**
 * TradeMatrixTemplateToRepresentativeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TradeMatrixTemplateToRepresentativeRepository extends \Doctrine\ORM\EntityRepository
{
}
