<?php

namespace ReservesBundle\Repository;

/**
 * TradeMatrixProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TradeMatrixProductRepository extends \Doctrine\ORM\EntityRepository
{
}
