<?php

namespace ReservesBundle\Repository;

/**
 * TradeMatrixCategoryCriteriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TradeMatrixCategoryCriteriaRepository extends \Doctrine\ORM\EntityRepository
{
}
