<?php

namespace ReservesBundle\Repository;

/**
 * TradeMatrixLimitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TradeMatrixLimitRepository extends \Doctrine\ORM\EntityRepository
{
}
