<?php

namespace ReservesBundle\Repository;

/**
 * ViewShipmentItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViewShipmentItemRepository extends \Doctrine\ORM\EntityRepository
{
}
