<?php

namespace ContentBundle\Repository;

/**
 * BaseProductNamingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseProductNamingRepository extends \Doctrine\ORM\EntityRepository
{
}
