<?php

namespace ContentBundle\Repository;

/**
 * BaseProductBarCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseProductBarCodeRepository extends \Doctrine\ORM\EntityRepository
{
    
    const BARCODE_PRIVATE_PREFIX = "VI";
    const BARCODE_PRIVATE_SUFFIX = "IV";
    const BARCODE_PRIVATE_LENGTH = 8;
    
    const BARCODE_PALLET_PREFIX = "P";
    const BARCODE_PRODUCT_PREFIX = "G";
    
}
