<?php

namespace ContentBundle\Repository;

/**
 * BaseProductMeasureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseProductMeasureRepository extends \Doctrine\ORM\EntityRepository
{
}
