<?php

namespace ContentBundle\Repository;

/**
 * BaseProductMergeLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseProductMergeLogRepository extends \Doctrine\ORM\EntityRepository
{
}
