<?php

namespace ContentBundle\Repository;

/**
 * BaseProductNamingFieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseProductNamingFieldRepository extends \Doctrine\ORM\EntityRepository
{
}
