<?php

namespace ContentBundle\Repository;

/**
 * BaseProductImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseProductImageRepository extends \Doctrine\ORM\EntityRepository
{
    const SIZE_XS = 'xs';
    const SIZE_SM = 'sm';
    const SIZE_MD = 'md';
    const SIZE_LG = 'lg';
    const SIZE_XL = 'xl';

    protected $sizes = [
        self::SIZE_XS => 60,
        self::SIZE_SM => 100,
        self::SIZE_MD => 200,
        self::SIZE_LG => 280,
        self::SIZE_XL => 800,
    ];

    public function buildSrc($path, $basename, $size)
    {
        if (empty($basename)) {
            return null;
        }

        return $path.'/'.$basename.'_'.$this->getSize($size).'.jpg';
    }

    public function getSize($size)
    {
        if (empty($this->sizes[$size])) {
            throw new \LogicException("Не верный размер изображения");
        }

        return $this->sizes[$size];
    }

    public function getSizes()
    {
        return $this->sizes;
    }
}
