<?php

namespace ContentBundle\Repository;

/**
 * BaseProductDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseProductDataRepository extends \Doctrine\ORM\EntityRepository
{
}
