<?php

namespace ContentBundle\Repository;

use Doctrine\ORM\Query\ResultSetMapping;

/**
 * BaseProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseProductRepository extends \Doctrine\ORM\EntityRepository
{
}
