<?php

namespace ContentBundle\Repository;

/**
 * BaseProductDescriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseProductDescriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
