<?php

namespace ContentBundle\Repository;

/**
 * BaseProductIndexingQueueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseProductIndexingQueueRepository extends \Doctrine\ORM\EntityRepository
{
}
