<?php

namespace ContentBundle\Repository;

/**
 * ColorCompositeSchemaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColorCompositeSchemaRepository extends \Doctrine\ORM\EntityRepository
{
}
