<?php

namespace ContentBundle\Repository;

/**
 * ColorPaletteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColorPaletteRepository extends \Doctrine\ORM\EntityRepository
{
}
