<?php

namespace ContentBundle\Repository;

/**
 * DetailValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailValueRepository extends \Doctrine\ORM\EntityRepository
{
}
