<?php

namespace ContentBundle\Repository;

/**
 * DetailTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
