<?php

namespace ContentBundle\Repository;

/**
 * DetailValueAliasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailValueAliasRepository extends \Doctrine\ORM\EntityRepository
{
}
