<?php

namespace ContentBundle\Repository;

/**
 * DetailGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
