<?php

namespace ContentBundle\Repository;

/**
 * FulfillmentLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FulfillmentLogRepository extends \Doctrine\ORM\EntityRepository
{
}
