<?php

namespace ContentBundle\Repository;

/**
 * FullnessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FullnessRepository extends \Doctrine\ORM\EntityRepository
{
}
