<?php

namespace ContentBundle\Repository;

/**
 * GeoCityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeoCityRepository extends \Doctrine\ORM\EntityRepository
{
}
