<?php

namespace ContentBundle\Repository;

/**
 * GeoRoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeoPointRepository extends \Doctrine\ORM\EntityRepository
{
}
