<?php

namespace ContentBundle\Repository;

use AppBundle\Entity\User;
use ContentBundle\Entity\Manager;

/**
 * ManagerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManagerRepository extends \Doctrine\ORM\EntityRepository
{
    public function check(User $user) 
    {
        $manager = $this->find($user->getId());
        if (!$manager instanceof Manager) {
            $manager = new Manager();
            $manager->setUserId($user->getId());
            $manager->setIsActive(true);
            $this->getEntityManager()->persist($manager);
            $this->getEntityManager()->flush($manager);
        }
    }
}
