<?php

namespace ContentBundle\Repository;

/**
 * MeasureUnitAliasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeasureUnitAliasRepository extends \Doctrine\ORM\EntityRepository
{
}
