<?php

namespace ContentBundle\Repository;

/**
 * MeasureUnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeasureUnitRepository extends \Doctrine\ORM\EntityRepository
{
}
