<?php

namespace ContentBundle\Repository;

/**
 * ParserDetailGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParserDetailGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
