<?php

namespace ContentBundle\Repository;

/**
 * ParserDetailToContentDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParserDetailToContentDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
