<?php

namespace ContentBundle\Repository;

/**
 * ParserSourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParserSourceRepository extends \Doctrine\ORM\EntityRepository
{
}
