<?php

namespace ContentBundle\Repository;

/**
 * ParserDetailToProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParserDetailToProductRepository extends \Doctrine\ORM\EntityRepository
{
}
