<?php

namespace ContentBundle\Repository;

/**
 * ParserDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParserDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
