<?php

namespace ContentBundle\Repository;

/**
 * ParserProductDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParserProductDataRepository extends \Doctrine\ORM\EntityRepository
{
}
