<?php

namespace ContentBundle\Repository;

/**
 * ParserImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParserImageRepository extends \Doctrine\ORM\EntityRepository
{
}
