<?php

namespace ContentBundle\Repository;

/**
 * SMLMarkdownReasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SMLMarkdownReasonRepository extends \Doctrine\ORM\EntityRepository
{
}
