<?php

namespace MatrixBundle\Repository;

/**
 * TradeMatrixTemplateProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TradeMatrixTemplateProductRepository extends \Doctrine\ORM\EntityRepository
{
}
