<?php

namespace MatrixBundle\Repository;

/**
 * TradeMatrixProductToRepresentativeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TradeMatrixProductToRepresentativeRepository extends \Doctrine\ORM\EntityRepository
{
}
