<?php

namespace MatrixBundle\Repository;

/**
 * TradeMatrixCategoryToRepresentativeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TradeMatrixCategoryToRepresentativeRepository extends \Doctrine\ORM\EntityRepository
{
}
