<?php

namespace ThirdPartyBundle\Repository;

/**
 * GeoAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeoAreaRepository extends \Doctrine\ORM\EntityRepository
{
}
