<?php

namespace ThirdPartyBundle\Repository;

/**
 * GeoBaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeoBaseRepository extends \Doctrine\ORM\EntityRepository
{
}
