<?php

namespace ThirdPartyBundle\Repository;

/**
 * GeoCitiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeoCitiesRepository extends \Doctrine\ORM\EntityRepository
{
}
