<?php

namespace ThirdPartyBundle\Repository;

/**
 * GeoRegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeoRegionRepository extends \Doctrine\ORM\EntityRepository
{
}
