<?php

namespace ThirdPartyBundle\Repository;

/**
 * GeoStreetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeoStreetRepository extends \Doctrine\ORM\EntityRepository
{
}
