<?php

namespace ThirdPartyBundle\Repository;

/**
 * GeoTempRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeoTempRepository extends \Doctrine\ORM\EntityRepository
{
}
