<?php

namespace ThirdPartyBundle\Repository;

/**
 * SystemParamsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemParamsRepository extends \Doctrine\ORM\EntityRepository
{
}
