services:
    city.identity:
        class: 'GeoBundle\Service\CityIdentity'
        public: true
        calls:
            - [ 'setContainer', [ '@service_container' ] ]

    representative.identity:
        class: 'GeoBundle\Service\RepresentativeIdentity'
        public: true
        calls:
            - [ 'setContainer', [ '@service_container' ] ]

    delivery.date:
        class: 'GeoBundle\Service\DeliveryDate'
        public: true 
        calls:
            - [ 'setContainer', [ '@service_container' ] ]

    phone.formater:
        class: 'GeoBundle\Service\PhoneFormater'
        public: true 
        calls:
            - [ 'setContainer', [ '@service_container' ] ]

    address.formatter:
        class: 'GeoBundle\Service\AddressFormatter'
        public: true 
        calls:
            - [ 'setContainer', [ '@service_container' ] ]
