services:
    supplier.pricelist.parser:
        class: ContentBundle\Bus\SupplierPricelist\Parser\Parser
        public: true
        arguments: [ '@spreadsheet.reader' ]

    supplier.pricelist.loader:
        class: ContentBundle\Bus\SupplierPricelist\Loader\Loader
        public: true
        calls:
            - [ setContainer, [ '@service_container' ] ]

    sml.scraper:
        class: ContentBundle\Bus\Supplier\SML\Scraper
        public: true
        calls:
            - [ setContainer, [ '@service_container' ] ]